export default {
  LOGIN: 'LOGIN',
  TOKEN: "TOKEN",
  API_REQUEST: "API_REQUEST",
  API_SUCCESS: "API_SUCCES",
  API_FAILURE: "API_FAILURE",
  API_LIST_END: "API_LIST_END",
  CHANGE_THEME: "CHANGE_THEME",
  CLEAR_REDUX_DATAID: "CLEAR_REDUX_DATAID",
  CLEAR_REDUX_DATA: "CLEAR_REDUX_DATA",
  CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
};
